name: Daily Selenium CI

on:
  push:          # Run on every push
  schedule:      # Run every day at 10:00 AM PKT (5:00 AM UTC)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium tests
        run: mvn clean compile exec:java
