name: Daily Selenium CI

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:    # Allows manual trigger

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Selenium tests
      run: mvn compile exec:java
