name: Daily + Push Selenium CI

on:
  push:
    branches:
      - master  # Change if your branch is 'main'
  schedule:
    - cron: '0 5 * * *'  # 10:00 AM Pakistan Time = 5:00 AM UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium tests
        run: mvn clean compile exec:java
